# Omakase Ruby styling for Rails
inherit_gem:
  rubocop-rails-omakase: rubocop.yml
require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  Exclude:
    - "bin/*"
    - "config/**/*"
    - "db/**/migrate/**/*"
    - "db/**/*schema.rb"
    - db/seeds.rb
    - "tmp/**/*"
    - "vendor/**/*"
    - lib/application_config_validator.rb
    - app/models/config.rb

Performance/ReverseEach:
  Enabled: true

Performance/TimesMap:
  Enabled: true

Performance/RegexpMatch:
  Enabled: true

Performance/StringReplacement:
  Enabled: true

Performance/Casecmp:
  Enabled: true

Performance/CollectionLiteralInLoop:
  Enabled: true

Performance/Detect:
  Enabled: true

Performance/DoubleStartEndWith:
  Enabled: true

Performance/FixedSize:
  Enabled: true

Performance/RedundantMerge:
  Enabled: true

Performance/Size:
  Enabled: true

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

Metrics/AbcSize:
  Max: 40

Metrics/ClassLength:
  Description: Class has too many lines
  Enabled: true
  Max: 200

Metrics/MethodLength:
  Max: 60

Metrics/BlockLength:
  Exclude:
    - "app/views/**/*"
    - "lib/tasks/*.rake"
    - "spec/**/*"
  Max: 50

Layout/LineLength:
  Max: 120

Layout/TrailingWhitespace:
  Enabled: true

Rails/SkipsModelValidations:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - production
    - staging
    - development
    - test

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Max: 10

RSpec/DescribeClass:
  Exclude:
    - "spec/lib/tasks/**/*"

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Performance/MethodObjectAsBlock:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5

RSpec/MessageSpies:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: true

Style/AccessorGrouping:
  Enabled: true

Style/Alias:
  Enabled: true

Style/AndOr:
  Enabled: true
  EnforcedStyle: always

Style/ArgumentsForwarding:
  Enabled: true

Style/ArrayCoercion:
  Enabled: false

Style/ArrayJoin:
  Enabled: true

Style/AsciiComments:
  Enabled: true
  AllowedChars:
    - €
    - 🙌

Style/AutoResourceCleanup:
  Enabled: false

Style/BarePercentLiterals:
  Enabled: true

Style/BeginBlock:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: true

Style/BlockComments:
  Enabled: true

Style/BlockDelimiters:
  Enabled: true

Style/CaseEquality:
  Enabled: false

Style/CaseLikeIf:
  Enabled: true

Style/CharacterLiteral:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassCheck:
  Enabled: true

Style/ClassEqualityComparison:
  Enabled: true

Style/ClassMethods:
  Enabled: true

Style/ClassMethodsDefinitions:
  Enabled: true

Style/ClassVars:
  Enabled: true

Style/CollectionCompact:
  Enabled: true

Style/CollectionMethods:
  Enabled: true
  PreferredMethods:
    collect: map
    collect!: map!
    inject: reduce
    find_all: select
    find: detect

Style/ColonMethodCall:
  Enabled: true

Style/ColonMethodDefinition:
  Enabled: true

Style/CombinableLoops:
  Enabled: true

Style/CommandLiteral:
  Enabled: true

Style/CommentAnnotation:
  Enabled: true
  Keywords:
    - TODO
    - FIXME
    - OPTIMIZE
    - HACK
    - REVIEW

Style/CommentedKeyword:
  Enabled: true

Style/ConditionalAssignment:
  Enabled: true

Style/Copyright:
  Enabled: false

Style/DateTime:
  Enabled: false

Style/DefWithParentheses:
  Enabled: true

Style/Dir:
  Enabled: true

Style/DisableCopsWithinSourceCodeDirective:
  Enabled: false

Style/DocumentDynamicEvalDefinition:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/DoubleCopDisableDirective:
  Enabled: true

Style/DoubleNegation:
  Enabled: true

Style/EachForSimpleLoop:
  Enabled: true

Style/EachWithObject:
  Enabled: true

Style/EmptyBlockParameter:
  Enabled: true

Style/EmptyCaseCondition:
  Enabled: true

Style/EmptyElse:
  Enabled: true

Style/EmptyHeredoc:
  Enabled: true

Style/EmptyLambdaParameter:
  Enabled: true

Style/EmptyLiteral:
  Enabled: true

Style/EmptyMethod:
  Enabled: true

Style/Encoding:
  Enabled: true

Style/EndBlock:
  Enabled: true

Style/EndlessMethod:
  Enabled: true

Style/EnvHome:
  Enabled: true

Style/EvalWithLocation:
  Enabled: true

Style/EvenOdd:
  Enabled: true

Style/ExpandPathArguments:
  Enabled: true

Style/ExplicitBlockArgument:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/FetchEnvVar:
  Enabled: false

Style/FileRead:
  Enabled: true

Style/FileWrite:
  Enabled: true

Style/FloatDivision:
  Enabled: true

Style/For:
  Enabled: true

Style/FormatString:
  Enabled: true

Style/FormatStringToken:
  Enabled: true
  EnforcedStyle: template

Style/FrozenStringLiteralComment:
  Enabled: true

Style/GlobalStdStream:
  Enabled: true

Style/GlobalVars:
  Enabled: true

Style/GuardClause:
  Enabled: true

Style/HashAsLastArrayItem:
  Enabled: true

Style/HashConversion:
  Enabled: true
  AllowSplatArgument: false

Style/HashEachMethods:
  Enabled: true

Style/HashExcept:
  Enabled: true

Style/HashLikeCase:
  Enabled: false

Style/HashSyntax:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/IdenticalConditionalBranches:
  Enabled: true

Style/IfInsideElse:
  Enabled: true

Style/IfUnlessModifier:
  Enabled: true

Style/IfUnlessModifierOfIfUnless:
  Enabled: true

Style/IfWithBooleanLiteralBranches:
  Enabled: true

Style/IfWithSemicolon:
  Enabled: true

Style/ImplicitRuntimeError:
  Enabled: false

Style/InPatternThen:
  Enabled: true

Style/InfiniteLoop:
  Enabled: true

Style/InlineComment:
  Enabled: false

Style/InverseMethods:
  Enabled: true

Style/IpAddresses:
  Enabled: false

Style/KeywordParametersOrder:
  Enabled: true

Style/Lambda:
  Enabled: true
  EnforcedStyle: literal

Style/LambdaCall:
  Enabled: true

Style/LineEndConcatenation:
  Enabled: true

Style/MagicCommentFormat:
  Enabled: true

Style/MapCompactWithConditionalBlock:
  Enabled: true

Style/MapToHash:
  Enabled: true

Style/MethodCallWithArgsParentheses:
  Enabled: true
  AllowedMethods:
    - raise
    - render
    - yield
    - step
    - preload
    - safe_call
    - assign_data
    - add_error
    -  # RSpec specific
    - and
    - describe
    - not_to
    - to
    # Not properly detected as a macro in exec blocks
    - attr_accessor
    - attr_reader
    - attr_writer

Style/MethodCallWithoutArgsParentheses:
  Enabled: true

Style/MethodCalledOnDoEndBlock:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: true

Style/MinMax:
  Enabled: true

Style/MissingRespondToMissing:
  Enabled: true

Style/MixinGrouping:
  Enabled: true

Style/MixinUsage:
  Enabled: true

Style/ModuleFunction:
  Enabled: true
  EnforcedStyle: extend_self

Style/MultilineBlockChain:
  Enabled: true

Style/MultilineIfModifier:
  Enabled: false

Style/MultilineIfThen:
  Enabled: true

Style/MultilineInPatternThen:
  Enabled: true

Style/MultilineMemoization:
  Enabled: true

Style/MultilineMethodSignature:
  Enabled: true

Style/MultilineTernaryOperator:
  Enabled: true

Style/MultilineWhenThen:
  Enabled: true

Style/MultipleComparison:
  Enabled: true

Style/MutableConstant:
  Enabled: true

Style/NegatedIf:
  Enabled: true

Style/NegatedIfElseCondition:
  Enabled: true

Style/NegatedUnless:
  Enabled: true

Style/NegatedWhile:
  Enabled: true

Style/NestedFileDirname:
  Enabled: true

Style/NestedModifier:
  Enabled: true

Style/NestedParenthesizedCalls:
  Enabled: true

Style/NestedTernaryOperator:
  Enabled: true

Style/Next:
  Enabled: true

Style/NilComparison:
  Enabled: true

Style/NilLambda:
  Enabled: true

Style/NonNilCheck:
  Enabled: true
  IncludeSemanticChanges: false

Style/Not:
  Enabled: true

Style/NumberedParameters:
  Enabled: true

Style/NumberedParametersLimit:
  Enabled: true

Style/NumericLiteralPrefix:
  Enabled: true

Style/NumericLiterals:
  Enabled: false

Style/NumericPredicate:
  Enabled: true

Style/ObjectThen:
  Enabled: true

Style/OneLineConditional:
  Enabled: true

Style/OpenStructUse:
  Enabled: true
  Exclude:
    - spec/**/*.rb

Style/OptionHash:
  Enabled: true

Style/OptionalArguments:
  Enabled: true

Style/OptionalBooleanParameter:
  Enabled: true

Style/OrAssignment:
  Enabled: true

Style/ParallelAssignment:
  Enabled: true

Style/ParenthesesAroundCondition:
  Enabled: true
